# rest.http the same postman
# install REST Client VSC Extension to Send Request
GET http://localhost:5000/course


###
GET http://localhost:5000/courses


###s

POST http://localhost:5000/users/register
Content-Type: application/json

{
    "email": "20522122@gm.uit.edu.vn",
    "firstname": "tuan",
    "lastname": "nguyen",
    "password": "tuannt02",
    "passwordConfirmation": "tuannt02"
}

###
GET http://localhost:5000/users


###
POST http://localhost:5000/users/login