# rest.http the same postman
# install REST Client VSC Extension to Send Request

### Check invalid route
GET http://localhost:5000/course


### Get all courses
GET http://localhost:5000/courses


### Register
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "email": "20522122@gm.uit.edu.vn",
    "firstname": "tuan",
    "lastname": "nguyen",
    "password": "tuannt02",
    "passwordConfirmation": "tuannt02"
}


### Get all user
GET http://localhost:5000/users


### Login
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "20522122@gm.uit.edu.vn",
    "password": "tuannt02"
}


### Get list
GET http://localhost:5000/users/getlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2OTU2MjEwOCwiZXhwIjoxNjY5NTY1NzA4fQ.Yi_kKvtmY2WaIlhT4u9Hg_Rj7LNSXCkQaK1PooXaGwU


### Refresh token
POST http://localhost:5000/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2OTU2MjEwOCwiZXhwIjoxNzAxMTE5NzA4fQ.F7TKLeOMkN_zQ4-yD127ttOC1hHxdja4rPvvQQq8Qv8"
}


### Logout
DELETE http://localhost:5000/users/logout
Content-Type: application/json


{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY2OTU2MzMyNiwiZXhwIjoxNzAxMTIwOTI2fQ.Jj7E7XXSKX1IUFs4v1_5XC2pAIMqLYa0gf_xHiA42nQ"
}

### Get lesson learned in week
GET http://localhost:5000/courses/4/learned-in-week/4

### Get list unit, lesson user in completed
GET http://localhost:5000/courses/4/unfinished-lesson/4