-- Flashcard type
CREATE TABLE flashcard_type (
  fc_type_id SERIAL PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  description TEXT,
  sets_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER update_db_timestamp BEFORE UPDATE
ON flashcard_type
FOR EACH ROW
EXECUTE PROCEDURE update_timestamp();

INSERT INTO flashcard_type(type, description) VALUES('IELTS', 'Flashcard liên quan tới IELTS. Học chúng sẽ giúp bạn làm bài thi IELTS mượt như cá gặp nước.');
INSERT INTO flashcard_type(type, description) VALUES('TOEIC', 'Cung cấp cho bạn hàng tỉ flashcard. Bạn sẽ không còn sợ khi làm bài thi TOEIC nữa.');
INSERT INTO flashcard_type(type, description) VALUES('Từ vựng hàng ngày', '10 phút mỗi ngày với những từ vựng này, sau 1 tháng bạn bỗng trở thành người bản xứ.');

-- Flashcard set
create table flashcard_set (
  fc_set_id SERIAL PRIMARY KEY,
  fc_type_id INTEGER REFERENCES flashcard_type(fc_type_id) ON DELETE CASCADE,
	description TEXT,
  words_count INTEGER DEFAULT 0,
	system_belong BOOLEAN DEFAULT false,
	access VARCHAR(16),
	views INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER update_db_timestamp BEFORE UPDATE
ON flashcard_set
FOR EACH ROW
EXECUTE PROCEDURE update_timestamp();

insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (3, 'Dilation of Left Anterior Tibial Artery with Four or More Drug-eluting Intraluminal Devices, Open Approach', true, 'public', 79);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (2, 'Extirpation of Matter from Left Lower Extremity Bursa and Ligament, Percutaneous Endoscopic Approach', false, 'private', 744);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Removal of Autologous Tissue Substitute from Left Metacarpal, Percutaneous Approach', false, 'public', 182);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (2, 'Occlusion of Anus with Intraluminal Device, Percutaneous Approach', true, 'private', 10);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (2, 'Drainage of Left Foot Subcutaneous Tissue and Fascia, Percutaneous Approach, Diagnostic', true, 'public', 455);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Excision of Tongue, Percutaneous Approach, Diagnostic', false, 'private', 436);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (3, 'Excision of Left Lower Extremity, Percutaneous Approach, Diagnostic', false, 'private', 84);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Bypass Right Pulmonary Artery from Carotid with Zooplastic Tissue, Open Approach', false, 'private', 36);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (3, 'Resection of Accessory Pancreatic Duct, Open Approach', true, 'public', 783);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (3, 'Cerumen Management Treatment using Cerumen Management Equipment', false, 'private', 248);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Bypass Right External Iliac Artery to Right Femoral Artery with Nonautologous Tissue Substitute, Open Approach', true, 'public', 472);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Destruction of Left Inner Ear, Open Approach', false, 'private', 997);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Supplement Ileocecal Valve with Autologous Tissue Substitute, Percutaneous Endoscopic Approach', false, 'public', 510);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Resection of Left Upper Extremity Bursa and Ligament, Percutaneous Endoscopic Approach', true, 'private', 526);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Extirpation of Matter from Phrenic Nerve, Percutaneous Approach', false, 'private', 997);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (3, 'Destruction of Left Retinal Vessel, Percutaneous Approach', true, 'public', 819);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (2, 'Reattachment of Right 2nd Toe, Open Approach', false, 'private', 521);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (2, 'Osteopathic Treatment of Cervical Region using Indirect Forces', false, 'public', 42);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Division of Lumbosacral Plexus, Open Approach', true, 'public', 910);
insert into flashcard_set (fc_type_id, description, system_belong, access, views) values (1, 'Drainage of Cervical Vertebral Joint with Drainage Device, Percutaneous Approach', true, 'public', 631);


-- Flashcard
create table flashcard (
  fc_id SERIAL PRIMARY KEY,
	fc_set_id INT REFERENCES flashcard_set(fc_set_id) ON DELETE CASCADE,
	word TEXT NOT NULL,
	meaning TEXT NOT NULL,
	type_of_word VARCHAR(15) NOT NULL,
	pronounce TEXT,
	example TEXT,
	note TEXT,
	image TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER update_db_timestamp BEFORE UPDATE
ON flashcard
FOR EACH ROW
EXECUTE PROCEDURE update_timestamp();

insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'ac', 'Toxic effect of contact with other venomous fish, intentional self-harm, sequela', 'tortor', 'Other specified injury of plantar artery of right foot, subsequent encounter', 'Partial traumatic transphalangeal amputation of right ring finger, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'convallis', 'Passenger on bus injured in collision with pedestrian or animal in nontraffic accident, sequela', 'semper', 'Other fracture of shaft of radius, right arm', 'Traumatic hemorrhage of right cerebrum without loss of consciousness, subsequent encounter', 'Other diseases of mediastinum, not elsewhere classified', 'http://dummyimage.com/121x100.png/ff4444/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'est', 'Displaced apophyseal fracture of unspecified femur, subsequent encounter for closed fracture with delayed healing', 'ipsum', 'Person boarding or alighting a pick-up truck or van injured in noncollision transport accident, initial encounter', 'Salter-Harris Type II physeal fracture of unspecified metatarsal, subsequent encounter for fracture with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'posuere', 'Infection of intervertebral disc (pyogenic), lumbar region', 'elit', 'Salter-Harris Type I physeal fracture of lower end of unspecified tibia, subsequent encounter for fracture with nonunion', 'Torus fracture of lower end of right tibia, subsequent encounter for fracture with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'non', 'Unspecified injury of stomach', 'iaculis', 'Nondisplaced articular fracture of head of right femur, subsequent encounter for open fracture type I or II with delayed healing', 'Unspecified dislocation of left patella, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'velit', 'Underdosing of other drugs, medicaments and biological substances', 'nisl', 'Other injury of unspecified urinary and pelvic organ, initial encounter', 'Adverse effect of antiallergic and antiemetic drugs', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'bibendum', 'Accidental malfunction of hunting rifle, sequela', 'ligula', 'Term delivery with preterm labor, unspecified trimester, fetus 4', 'Contusion of unspecified middle finger without damage to nail', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'lectus', 'Other tear of medial meniscus, current injury, unspecified knee, subsequent encounter', 'fermentum', 'Blister (nonthermal) of right elbow, initial encounter', 'Personal history of diseases of the digestive system', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'velit', 'Acute recurrent tonsillitis, unspecified', 'quam', 'Other skin changes due to chronic exposure to nonionizing radiation', 'Poisoning by unspecified psychodysleptics [hallucinogens], intentional self-harm, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'vel', 'Neoplasm of unspecified behavior of other specified sites', 'penatibus', 'Underdosing of antitussives, sequela', 'Corrosion of unspecified degree of right thigh, sequela', 'Poisoning by tricyclic antidepressants, intentional self-harm, initial encounter', 'http://dummyimage.com/216x100.png/5fa2dd/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'ligula', 'Thoracoabdominal aortic ectasia', 'vitae', 'Unspecified superficial injuries of throat', 'Injury of other nerves at wrist and hand level of left arm', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'magnis', 'Unspecified occupant of special industrial vehicle injured in traffic accident, subsequent encounter', 'amet', 'Juvenile osteochondrosis of hip and pelvis', 'Atherosclerosis of autologous vein bypass graft(s) of the extremities with gangrene, right leg', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'justo', 'Deep dyspareunia', 'vivamus', 'Puncture wound without foreign body, right thigh, initial encounter', 'Nondisplaced fracture of body of scapula, left shoulder, subsequent encounter for fracture with delayed healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (14, 'tellus', 'Nondisplaced transverse fracture of shaft of left radius, subsequent encounter for closed fracture with delayed healing', 'rutrum', 'Diverticulitis of both small and large intestine without perforation or abscess with bleeding', 'Nondisplaced spiral fracture of shaft of radius, unspecified arm, initial encounter for open fracture type I or II', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'enim', 'Basal cell carcinoma of skin of lower limb, including hip', 'luctus', 'Toxic effect of harmful algae and algae toxins, accidental (unintentional), initial encounter', 'Other injury due to other accident to water-skis, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'sagittis', 'Person on outside of car injured in collision with two- or three-wheeled motor vehicle in nontraffic accident, initial encounter', 'primis', 'Pathological fracture, right shoulder, subsequent encounter for fracture with nonunion', 'Infection and inflammatory reaction due to unspecified internal joint prosthesis', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'ipsum', 'Nondisplaced fracture of lower epiphysis (separation) of unspecified femur, subsequent encounter for open fracture type I or II with delayed healing', 'nisi', 'Laceration of abdominal wall with foreign body, right upper quadrant without penetration into peritoneal cavity', 'Other injury of muscle, fascia and tendon of pelvis', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'ut', 'Nondisplaced supracondylar fracture without intracondylar extension of lower end of unspecified femur, subsequent encounter for open fracture type I or II with delayed healing', 'sollicitudin', 'Dislocation of T8/T9 thoracic vertebra, initial encounter', 'Nondisplaced spiral fracture of shaft of ulna, unspecified arm, subsequent encounter for closed fracture with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'rutrum', 'Laceration of muscle, fascia and tendon of right hip, sequela', 'nibh', 'Twin pregnancy, unspecified number of placenta and unspecified number of amniotic sacs, second trimester', 'Flexion deformity, right hip', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (14, 'auctor', 'Crowding of fully erupted teeth', 'dapibus', 'Fall from non-in-line roller-skates', 'Poisoning by other nonopioid analgesics and antipyretics, not elsewhere classified, intentional self-harm, initial encounter', 'Intervertebral disc stenosis of neural canal of thoracic region', 'http://dummyimage.com/157x100.png/ff4444/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'amet', 'Cholesteatoma of attic, bilateral', 'integer', 'Person on outside of car injured in collision with other nonmotor vehicle in traffic accident', 'Subluxation of proximal interphalangeal joint of left ring finger, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'cras', 'Nondisplaced fracture of greater trochanter of unspecified femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'quisque', 'Disease of esophagus, unspecified', 'Nondisplaced fracture (avulsion) of medial epicondyle of left humerus, initial encounter for closed fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'nascetur', 'Non-pressure chronic ulcer of left thigh with necrosis of muscle', 'primis', 'Toxic effect of unspecified pesticide, accidental (unintentional), initial encounter', 'Toxic effect of venom of other arthropods', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'mollis', 'Puncture wound with foreign body, left knee, initial encounter', 'mi', 'Other fracture of lower end of left ulna, subsequent encounter for open fracture type I or II with nonunion', 'Other mechanical complication of indwelling ureteral stent, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'diam', 'Finding of unspecified substance, not normally found in blood', 'ante', 'Secondary malignant neoplasm of unspecified respiratory organ', 'Partial traumatic transphalangeal amputation of left ring finger, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'rutrum', 'Pedestrian on skateboard injured in collision with heavy transport vehicle or bus, unspecified whether traffic or nontraffic accident', 'dolor', 'Encounter for orthopedic aftercare following scoliosis surgery', 'Explosion and rupture of other pressurized tire, pipe or hose, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'habitasse', 'Nondisplaced fracture of right tibial spine, subsequent encounter for closed fracture with nonunion', 'ligula', 'Burn of third degree of multiple sites of ankle and foot', 'Blister (nonthermal), left lesser toe(s), sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'magna', 'Neonatal aspiration of milk and regurgitated food', 'odio', 'Displaced fracture of neck of unspecified talus, initial encounter for open fracture', 'Other fracture of right patella, subsequent encounter for open fracture type I or II with malunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'eget', 'Stress fracture, left finger(s), subsequent encounter for fracture with nonunion', 'dapibus', 'Displaced fracture of proximal phalanx of left little finger, subsequent encounter for fracture with routine healing', 'Torus fracture of lower end of left humerus, initial encounter for closed fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'enim', 'Cerebral infarction due to embolism of right cerebellar artery', 'in', 'Other injury of other specified muscles, fascia and tendons at thigh level, left thigh, subsequent encounter', 'Other specified diabetes mellitus with diabetic macular edema, resolved following treatment, unspecified eye', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'ligula', 'Spontaneous rupture of flexor tendons, ankle and foot', 'nibh', 'Disorder of carnitine metabolism, unspecified', 'Subluxation and dislocation of lumbar vertebra', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'nulla', 'Poisoning by unspecified drugs acting on muscles, intentional self-harm', 'nulla', 'Toxic effects of unspecified halogen derivatives of aliphatic and aromatic hydrocarbons', 'Unspecified fracture of skull, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'et', 'Corrosions involving 40-49% of body surface with 10-19% third degree corrosion', 'vestibulum', 'Displaced avulsion fracture (chip fracture) of unspecified talus, sequela', 'Unspecified open wound of right wrist, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (7, 'nec', 'Salter-Harris Type I physeal fracture of upper end of right tibia', 'mauris', 'Blister (nonthermal) of right little finger', 'Assault by drowning and submersion while in swimming pool', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'vestibulum', 'Nondisplaced fracture of right tibial spine, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', 'arcu', 'Person injured in other specified (collision)(noncollision) transport accidents involving nonmotor vehicle, nontraffic, sequela', 'Laceration of extensor muscle, fascia and tendon of left index finger at forearm level, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'tristique', 'Displaced fracture of distal phalanx of unspecified thumb, subsequent encounter for fracture with nonunion', 'platea', 'Neoplasm of uncertain behavior of female genital organ, unspecified', 'Fall into other water striking bottom causing other injury, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'ac', 'Osseous stenosis of neural canal of abdomen and other regions', 'sapien', 'Displaced segmental fracture of shaft of radius, unspecified arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'Diverticulitis of both small and large intestine with perforation and abscess without bleeding', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'dis', 'Atherosclerosis of bypass graft of coronary artery of transplanted heart with unstable angina', 'in', 'Military operations involving destruction of aircraft due to collision with other aircraft', 'Unspecified fracture of left foot, initial encounter for open fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'in', 'Other sprain of left index finger', 'blandit', 'Poisoning by appetite depressants, undetermined, subsequent encounter', 'Factitious disorder with combined psychological and physical signs and symptoms', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (7, 'nulla', 'Laceration of flexor muscle, fascia and tendon of right middle finger at forearm level, sequela', 'cras', 'Unspecified retained (old) intraocular foreign body, nonmagnetic, bilateral', 'Wheelchair (powered) colliding with stationary object, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'augue', 'Nondisplaced comminuted fracture of shaft of right fibula, subsequent encounter for open fracture type I or II with malunion', 'libero', 'Underdosing of inhaled anesthetics, subsequent encounter', 'Other injury of adrenal gland, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'parturient', 'Nondisplaced spiral fracture of shaft of ulna, right arm, subsequent encounter for open fracture type I or II with nonunion', 'nascetur', 'Abrasion of right ring finger, sequela', 'Salter-Harris Type II physeal fracture of lower end of left femur, subsequent encounter for fracture with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'libero', 'Pathological fracture in other disease, unspecified hand, subsequent encounter for fracture with routine healing', 'dui', 'Puncture wound with foreign body of unspecified lesser toe(s) with damage to nail', 'Unspecified injury of femoral artery, left leg, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'maecenas', 'Displaced oblique fracture of shaft of right femur, initial encounter for open fracture type IIIA, IIIB, or IIIC', 'quis', 'Postdysenteric arthropathy, hand', 'Open bite of unspecified ear, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'pulvinar', 'Sprain of unspecified site of unspecified knee, subsequent encounter', 'congue', 'Other spondylosis, sacral and sacrococcygeal region', 'Driver of three-wheeled motor vehicle injured in collision with other nonmotor vehicle in traffic accident, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'eget', 'Occlusion and stenosis of right anterior cerebral artery', 'a', 'Hodgkin lymphoma, unspecified, lymph nodes of head, face, and neck', 'Acute duodenal ulcer with perforation', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'et', 'Displaced fracture of neck of left talus, subsequent encounter for fracture with delayed healing', 'curae', 'Other ambulatory health services establishments as the place of occurrence of the external cause', 'Poisoning by iminostilbenes, undetermined, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'dolor', 'Displaced fracture of right tibial tuberosity, sequela', 'vivamus', 'Unspecified retained (old) intraocular foreign body, nonmagnetic, left eye', 'Continuing pregnancy after elective fetal reduction of one fetus or more, first trimester, not applicable or unspecified', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'sit', 'Passenger in heavy transport vehicle injured in collision with other nonmotor vehicle in traffic accident, initial encounter', 'posuere', 'Unspecified malignant neoplasm of skin of trunk', 'Displaced transverse fracture of shaft of left fibula, initial encounter for open fracture type I or II', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'in', 'Burn of cornea and conjunctival sac, unspecified eye, subsequent encounter', 'et', 'Other specified injury of unspecified tibial artery, unspecified leg', 'Pedestrian with other conveyance injured in collision with railway train or railway vehicle, unspecified whether traffic or nontraffic accident', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'nunc', 'Minor laceration of vertebral artery', 'vel', 'Displaced comminuted fracture of unspecified patella, subsequent encounter for closed fracture with nonunion', 'Legal intervention involving injury by rubber bullet, bystander injured', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'habitasse', 'Complete traumatic amputation of right shoulder and upper arm, level unspecified, sequela', 'lacus', 'Post-traumatic osteoarthritis, right elbow', 'Other fracture of T9-T10 vertebra', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'vulputate', 'Idiopathic chronic gout, left shoulder, without tophus (tophi)', 'neque', 'Retained (nonmagnetic) (old) foreign body in vitreous body, unspecified eye', 'Fracture of first metacarpal bone', 'Corrosion of third degree of neck, subsequent encounter', 'http://dummyimage.com/121x100.png/dddddd/000000');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'nisl', 'Laceration with foreign body of anus', 'erat', 'Unspecified open wound of left ear', 'Food in bronchus causing asphyxiation, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'cubilia', 'Pre-existing hypertensive heart disease complicating pregnancy, unspecified trimester', 'mattis', 'Other superficial bite of penis', 'Reversible pulpitis', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'nisi', 'Nondisplaced spiral fracture of shaft of left femur, subsequent encounter for open fracture type I or II with delayed healing', 'vestibulum', 'Type 1 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, left eye', 'Abscess of eyelid', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'ullamcorper', 'Person on outside of car injured in collision with van in traffic accident, sequela', 'hac', 'Other difficulties with micturition', 'Other secondary cataract, unspecified eye', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'ac', 'Sedative, hypnotic or anxiolytic use, unspecified with sedative, hypnotic or anxiolytic-induced psychotic disorder', 'erat', 'Laceration of flexor muscle, fascia and tendon of left middle finger at wrist and hand level, initial encounter', 'Displaced fracture of neck of first metacarpal bone, unspecified hand, subsequent encounter for fracture with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'vehicula', 'Other abnormal findings in cerebrospinal fluid', 'purus', 'Adverse effect of enzymes, initial encounter', 'Toxic effect of venom of caterpillars, undetermined', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'volutpat', 'Displaced oblique fracture of shaft of unspecified ulna, initial encounter for open fracture type IIIA, IIIB, or IIIC', 'sed', 'Non-pressure chronic ulcer of unspecified part of unspecified lower leg with necrosis of muscle', 'Unilateral femoral hernia, with gangrene, not specified as recurrent', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'ipsum', 'Observation and evaluation of newborn for suspected neurological condition ruled out', 'quam', 'Displaced fracture of base of neck of unspecified femur, subsequent encounter for closed fracture with delayed healing', 'NIHSS score 42', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'posuere', 'Neonatal skin infection', 'sapien', 'Salter-Harris Type I physeal fracture of upper end of radius, left arm', 'Nondisplaced fracture of epiphysis (separation) (upper) of left femur, subsequent encounter for closed fracture with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'semper', 'Hormone sensitive malignancy status', 'orci', 'Rheumatoid vasculitis with rheumatoid arthritis of elbow', 'Strain of muscle, fascia and tendon of other parts of biceps, right arm, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'metus', 'Accidental drowning and submersion while in swimming-pool, subsequent encounter', 'nisl', 'Fistula, right shoulder', 'Laceration without foreign body, unspecified thigh', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'massa', 'Hydrocele, unspecified', 'sit', 'Acute leukemia of unspecified cell type, in relapse', 'Unspecified injury of extensor muscle, fascia and tendon of left ring finger at wrist and hand level', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'felis', 'Calcification and ossification of muscles associated with burns, other site', 'viverra', 'Poisoning by unspecified general anesthetics, intentional self-harm, subsequent encounter', 'Corrosion of third degree of single right finger (nail) except thumb, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'in', 'Corrosion of second degree of nose (septum), initial encounter', 'hac', 'Poisoning by enzymes, accidental (unintentional)', 'Nondisplaced spiral fracture of shaft of ulna, right arm', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'proin', 'Toxic effect of venom of caterpillars, accidental (unintentional)', 'ante', 'Underdosing of glucocorticoids and synthetic analogues, sequela', 'Alternating exotropia', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'amet', 'Laceration of blood vessel of left little finger, subsequent encounter', 'quis', 'Unspecified dacryocystitis of left lacrimal passage', 'Strain of right Achilles tendon, initial encounter', 'Abscess of breast associated with the puerperium', 'http://dummyimage.com/153x100.png/5fa2dd/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'nulla', 'Fall into unspecified water causing drowning and submersion, subsequent encounter', 'primis', 'Explosion of bicycle tire, subsequent encounter', 'Poisoning by pertussis vaccine, including combinations with a pertussis component, assault, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'sit', 'Accidental kick by another person, subsequent encounter', 'sit', 'Pathological fracture in other disease, right shoulder, subsequent encounter for fracture with malunion', 'Displaced spiral fracture of shaft of radius, right arm, initial encounter for open fracture type I or II', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (18, 'sed', 'Corrosion of second degree of abdominal wall, subsequent encounter', 'interdum', 'Food in bronchus causing other injury, subsequent encounter', 'Rh incompatibility with acute hemolytic transfusion reaction, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'iaculis', 'Nondisplaced segmental fracture of shaft of radius, unspecified arm, subsequent encounter for closed fracture with delayed healing', 'duis', 'NIHSS score 41', 'Laceration with foreign body of oral cavity, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'quis', 'Drowning and submersion due to other accident to (nonpowered) inflatable craft, sequela', 'in', 'Other fracture of first metacarpal bone, right hand, sequela', 'Antepartum hemorrhage, unspecified, unspecified trimester', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'vestibulum', 'Flat anterior chamber hypotony of right eye', 'ut', 'Internuclear ophthalmoplegia, left eye', 'Chronic osteomyelitis with draining sinus, right hand', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'feugiat', 'Melanocytic nevi of eyelid, including canthus', 'vestibulum', 'Displaced avulsion fracture (chip fracture) of left talus, subsequent encounter for fracture with delayed healing', 'Nondisplaced spiral fracture of shaft of radius, right arm, subsequent encounter for open fracture type I or II with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'eleifend', 'Malignant neoplasm of thyroid gland', 'vulputate', 'Maternal care for disproportion due to hydrocephalic fetus, fetus 1', 'Toxic effect of soaps, intentional self-harm, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'morbi', 'Cytomegaloviral mononucleosis', 'luctus', 'Pedal cycle driver injured in collision with other nonmotor vehicle in nontraffic accident', 'Resistance to other single specified antibiotic', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'erat', 'Osteitis deformans of right lower leg', 'eu', 'Military operations involving destruction of aircraft due to onboard fire, military personnel', 'Anterior dislocation of left ulnohumeral joint', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'etiam', 'Other specified injuries of left shoulder and upper arm, initial encounter', 'dolor', 'Foreign body in right ear, initial encounter', 'Unspecified fracture of second metacarpal bone, right hand, subsequent encounter for fracture with malunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'sed', 'Toxic effect of methanol', 'sollicitudin', 'Displaced fracture of cuboid bone of right foot, subsequent encounter for fracture with delayed healing', 'Age-related osteoporosis with current pathological fracture, unspecified ankle and foot, subsequent encounter for fracture with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (18, 'a', 'Displaced segmental fracture of shaft of radius, left arm', 'congue', 'Pressure ulcer of left hip, stage 1', 'Pauciarticular juvenile rheumatoid arthritis, ankle and foot', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'dolor', 'Dislocation of distal radioulnar joint of right wrist', 'curabitur', 'Blister (nonthermal) of abdomen, lower back, pelvis and external genitals', 'Fracture of unspecified part of scapula, right shoulder, subsequent encounter for fracture with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'sapien', 'Acquired clawhand', 'vel', 'Sprain of joints and ligaments of other parts of neck, sequela', 'Anaphylactic reaction due to serum', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'lorem', 'Injury of other nerves at lower leg level, unspecified leg', 'ipsum', 'Dislocation of distal interphalangeal joint of right thumb, sequela', 'Mouth breathing', 'Spondylosis', 'http://dummyimage.com/207x100.png/5fa2dd/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'nisi', 'Nondisplaced spiral fracture of shaft of humerus, right arm, subsequent encounter for fracture with routine healing', 'cursus', 'Commercial fixed-wing aircraft crash injuring occupant, initial encounter', 'Type 2 diabetes mellitus with moderate nonproliferative diabetic retinopathy without macular edema', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (7, 'amet', 'Ataxia following other cerebrovascular disease', 'venenatis', 'Other juvenile arthritis, right wrist', 'Injury of trochlear nerve, right side, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'vivamus', 'Open bite of unspecified toe(s) with damage to nail, initial encounter', 'pulvinar', 'ABO incompatibility reaction due to transfusion of blood or blood products, unspecified, subsequent encounter', 'Nondisplaced fracture of capitate [os magnum] bone, unspecified wrist, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'tempor', 'Osteonecrosis due to drugs, right ankle', 'in', 'Displaced other fracture of tuberosity of left calcaneus, initial encounter for open fracture', 'Contact with garden tool', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'vestibulum', 'Frostbite with tissue necrosis of right ankle, subsequent encounter', 'donec', 'Displacement of implanted electronic neurostimulator, generator', 'Displaced other fracture of tuberosity of right calcaneus, initial encounter for open fracture', 'Pathological gambling', 'http://dummyimage.com/216x100.png/ff4444/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'donec', 'Separation of muscle (nontraumatic), left forearm', 'ut', 'Toxic effect of chewing tobacco, accidental (unintentional), initial encounter', 'Congenital kyphosis, cervical region', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'tellus', 'Echinococcosis, other and unspecified', 'pretium', 'Underdosing of macrolides, initial encounter', 'Encounter for examination of eyes and vision with abnormal findings', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'neque', 'Fracture of unspecified phalanx of left thumb, sequela', 'vivamus', 'Other specified intracranial injury with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness', 'Type 1 diabetes mellitus with periodontal disease', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'justo', 'Displaced fracture of medial cuneiform of right foot, initial encounter for closed fracture', 'iaculis', 'Corrosion of third degree of lower back', 'Acquired epidermolysis bullosa, unspecified', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'quam', 'Drowning and submersion due to falling or jumping from crushed passenger ship', 'cubilia', 'Laceration of flexor muscle, fascia and tendon of right middle finger at wrist and hand level, subsequent encounter', 'Unspecified superficial injury of left hip, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (7, 'ac', 'Library as the place of occurrence of the external cause', 'magna', 'Sprain of the superior tibiofibular joint and ligament, right knee, subsequent encounter', 'Occupational exposure to toxic agents in agriculture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'molestie', 'Frostbite with tissue necrosis of right knee and lower leg', 'vehicula', 'Salter-Harris Type II physeal fracture of upper end of radius, right arm, sequela', 'Toxic effect of hydrogen sulfide, intentional self-harm, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (16, 'tincidunt', 'Post-traumatic osteoarthritis, unspecified ankle and foot', 'lacinia', 'Other osteoporosis with current pathological fracture, right shoulder', 'Congenital absence of bladder and urethra', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'in', 'Maternal care for known or suspected placental insufficiency, first trimester, fetus 5', 'faucibus', 'Person on outside of bus injured in collision with railway train or railway vehicle in traffic accident, sequela', 'Caught, crushed, jammed, or pinched between stationary objects, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'quam', 'Interstate highway as the place of occurrence of the external cause', 'justo', 'Blister (nonthermal) of right shoulder, subsequent encounter', 'Adverse effect of unspecified drugs acting on muscles, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'dolor', 'Nondisplaced unspecified condyle fracture of lower end of unspecified femur, subsequent encounter for open fracture type I or II with routine healing', 'donec', 'Other exposure to controlled fire in building or structure', 'Chondritis and perichondritis of external ear', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'lectus', 'Nondisplaced segmental fracture of shaft of unspecified fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 'integer', 'Nondisplaced fracture of medial condyle of unspecified tibia, subsequent encounter for open fracture type I or II with routine healing', 'Type III occipital condyle fracture, right side, subsequent encounter for fracture with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'auctor', 'Puncture wound without foreign body, left knee, sequela', 'nullam', 'Laceration of unspecified muscle and tendon at ankle and foot level, unspecified foot', 'Blindness, one eye, low vision other eye', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'erat', 'Burn of third degree of scalp [any part], initial encounter', 'eget', 'War operations involving flamethrower', 'Small kidney, unilateral', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'ante', 'Nondisplaced fracture of body of hamate [unciform] bone, right wrist, subsequent encounter for fracture with nonunion', 'imperdiet', 'Toxic effect of nitroglycerin and other nitric acids and esters, intentional self-harm, subsequent encounter', 'Goniosynechiae, right eye', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'suspendisse', 'Burn of third degree of multiple sites of unspecified lower limb, except ankle and foot, initial encounter', 'natoque', 'Nondisplaced fracture of head of unspecified radius, initial encounter for open fracture type I or II', 'Other infective (teno)synovitis, left ankle and foot', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'nulla', 'Nondisplaced unspecified fracture of right great toe, initial encounter for closed fracture', 'vel', 'Pathological fracture in other disease, left femur', 'Non-pressure chronic ulcer of left ankle with unspecified severity', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'in', 'Chronic post-thoracotomy pain', 'augue', 'Unspecified fracture of facial bones, sequela', 'Unspecified open wound of penis, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'ante', 'Incomplete lesion of sacral spinal cord', 'dapibus', 'Collapsed vertebra, not elsewhere classified, cervicothoracic region, initial encounter for fracture', 'Displaced simple supracondylar fracture without intercondylar fracture of right humerus, subsequent encounter for fracture with delayed healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'ante', 'Other superficial bite of ankle, unspecified ankle, subsequent encounter', 'ut', 'Toxic effect of fusel oil, intentional self-harm', 'Laceration of other extensor muscle, fascia and tendon at forearm level, left arm', 'Toxic effect of venom of wasps, assault, initial encounter', 'http://dummyimage.com/184x100.png/ff4444/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'curabitur', 'Gout due to renal impairment, unspecified hip', 'blandit', 'Laceration without foreign body of abdominal wall, right upper quadrant with penetration into peritoneal cavity', 'Unspecified fracture of shaft of unspecified fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'justo', 'Morquio A mucopolysaccharidoses', 'habitasse', 'Nondisplaced transverse fracture of shaft of unspecified femur, subsequent encounter for closed fracture with routine healing', 'Unspecified fracture of the lower end of unspecified radius, subsequent encounter for open fracture type I or II with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'donec', 'Contusion of left index finger without damage to nail', 'ante', 'Anaphylactic reaction due to food additives, initial encounter', 'Passenger in three-wheeled motor vehicle injured in collision with pedal cycle in nontraffic accident, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'vitae', 'Nondisplaced fracture of base of third metacarpal bone, right hand, subsequent encounter for fracture with malunion', 'accumsan', 'Other specified fracture of ischium', 'Displacement of implanted electronic neurostimulator of peripheral nerve electrode (lead)', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'ut', 'Lymphocyte depleted Hodgkin lymphoma, unspecified site', 'vel', 'Unspecified injury of greater saphenous vein at hip and thigh level, unspecified leg, sequela', 'Unspecified complication of procedure, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'tortor', 'Poisoning by antirheumatics, not elsewhere classified, assault, subsequent encounter', 'cras', 'Motorcycle driver injured in collision with car, pick-up truck or van in traffic accident, subsequent encounter', 'Corrosion of second degree of toe(s) (nail)', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'sit', 'Fracture of left shoulder girdle, part unspecified, initial encounter for closed fracture', 'posuere', 'Choroidal rupture', 'Glaucoma secondary to eye trauma, left eye, indeterminate stage', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'auctor', 'Blister (nonthermal), left knee, sequela', 'volutpat', 'Nondisplaced fracture of right tibial tuberosity, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'Asphyxiation due to being trapped in bed linens, assault, subsequent encounter', 'Other myositis, right upper arm', 'http://dummyimage.com/140x100.png/dddddd/000000');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'tellus', 'Age-related osteoporosis with current pathological fracture, left ankle and foot, subsequent encounter for fracture with delayed healing', 'integer', 'Corrosion of first degree of unspecified knee, initial encounter', 'Unspecified firearm discharge, undetermined intent', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'vel', 'Mononeuropathy, unspecified', 'congue', 'Other helminthiases', 'Fall on same level from slipping, tripping and stumbling without subsequent striking against object, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'morbi', 'Nondisplaced fracture of medial malleolus of left tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 'ut', 'Contusion of left thumb with damage to nail, sequela', 'Pigmentary glaucoma, right eye, severe stage', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'non', 'Recurrent dislocation, unspecified hip', 'ultrices', 'Other superficial bite of right eyelid and periocular area, initial encounter', 'Infection of amniotic sac and membranes, unspecified, unspecified trimester, not applicable or unspecified', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (18, 'etiam', 'Displaced intertrochanteric fracture of right femur, subsequent encounter for open fracture type I or II with malunion', 'nam', 'Acute on chronic slipped upper femoral epiphysis (nontraumatic), unspecified hip', 'Complex tear of medial meniscus, current injury, right knee, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'aliquet', 'Adhesions due to foreign body accidentally left in body following endoscopic examination, initial encounter', 'pede', 'Toxic effect of lacrimogenic gas, undetermined, sequela', 'Other osteoporosis with current pathological fracture, left humerus, initial encounter for fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (14, 'vestibulum', 'Displaced fracture of epiphysis (separation) (upper) of unspecified femur, initial encounter for open fracture type I or II', 'at', 'Bitten by nonvenomous snake', 'Aortic aneurysm of unspecified site, without rupture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'vel', 'Unspecified fracture of unspecified femur, subsequent encounter for closed fracture with malunion', 'vulputate', 'Benign neoplasm of unspecified part of small intestine', 'Displaced oblique fracture of shaft of unspecified ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'dapibus', 'Subluxation of T5/T6 thoracic vertebra, sequela', 'dui', 'Nondisplaced oblique fracture of shaft of unspecified femur, subsequent encounter for open fracture type I or II with nonunion', 'Chronic postrheumatic arthropathy [Jaccoud], hand', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'in', 'Other displaced fracture of upper end of unspecified humerus, subsequent encounter for fracture with routine healing', 'amet', 'Poisoning by oxytocic drugs, assault, sequela', 'Unspecified superficial injuries of breast, left breast, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'sapien', 'Malignant neoplasm of right choroid', 'in', 'Other osteoporosis with current pathological fracture, left shoulder, sequela', 'Poisoning by enzymes, assault, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'vel', 'Immunization not carried out for other reason', 'vulputate', 'Osteitis deformans of vertebrae', 'Burn of unspecified degree of unspecified axilla, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'augue', 'Nondisplaced spiral fracture of shaft of ulna, unspecified arm, subsequent encounter for closed fracture with malunion', 'dapibus', 'Worries', 'Salter-Harris Type III physeal fracture of lower end of ulna, left arm, initial encounter for closed fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'tortor', 'Other bursal cyst, right shoulder', 'a', 'Passenger in three-wheeled motor vehicle injured in collision with pedestrian or animal in nontraffic accident, subsequent encounter', 'Other chronic hematogenous osteomyelitis, left ankle and foot', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'dis', 'Blepharochalasis left lower eyelid', 'vivamus', 'External constriction of unspecified elbow, sequela', 'Malignant neoplasm of overlapping sites of other parts of mouth', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (18, 'mauris', 'Dissociative identity disorder', 'tincidunt', 'Adverse effect of calcium-channel blockers, initial encounter', 'Other specified fracture of unspecified acetabulum, initial encounter for closed fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'in', 'Unspecified occupant of bus injured in collision with heavy transport vehicle or bus in traffic accident, subsequent encounter', 'est', 'Neoplasm of uncertain behavior of respiratory organ, unspecified', 'Corrosion of second degree of shoulder and upper limb, except wrist and hand, unspecified site, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'luctus', 'Laceration of unspecified blood vessel at hip and thigh level', 'vestibulum', 'Fall on same level due to ice and snow, sequela', 'Blister (nonthermal), right knee, initial encounter', 'Neoplasm of unspecified behavior of endocrine glands and other parts of nervous system', 'http://dummyimage.com/203x100.png/5fa2dd/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'nulla', 'Other derangements of patella', 'vel', 'Unspecified fracture of shaft of unspecified ulna, sequela', 'Puncture wound without foreign body of scalp, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'dictumst', 'Displaced transverse fracture of shaft of left tibia, subsequent encounter for closed fracture with delayed healing', 'at', 'Poisoning by other parasympathomimetics [cholinergics], assault, subsequent encounter', 'Poisoning by unspecified agents primarily affecting the gastrointestinal system, undetermined, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (5, 'tempus', 'Postprocedural hemorrhage of right eye and adnexa following an ophthalmic procedure', 'vel', 'Incompetence or weakening of pubocervical tissue', 'Unspecified superficial injury of unspecified foot, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'volutpat', 'Stable burst fracture of first lumbar vertebra, subsequent encounter for fracture with routine healing', 'sem', 'Other infective (teno)synovitis, left wrist', 'Unspecified focal traumatic brain injury with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'amet', 'Other varicella complications', 'platea', 'Immersion foot, right foot', 'Malignant hyperthermia due to anesthesia, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'ante', 'Displaced fracture of head of right radius, subsequent encounter for closed fracture with delayed healing', 'amet', 'Unspecified occupant of heavy transport vehicle injured in collision with other nonmotor vehicle in nontraffic accident, subsequent encounter', 'Displaced fracture of left radial styloid process, initial encounter for open fracture type IIIA, IIIB, or IIIC', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'mattis', 'Unspecified superficial injury of left eyelid and periocular area, sequela', 'ligula', 'Unspecified injury of lesser saphenous vein at lower leg level, unspecified leg, initial encounter', 'Burn of unspecified degree of upper back, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'convallis', 'Neoplasm of uncertain behavior of female genital organ, unspecified', 'justo', 'Retained (nonmagnetic) (old) foreign body in lens', 'Unspecified injury of tail of pancreas, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'nulla', 'Superficial foreign body, right ankle, sequela', 'vulputate', 'Cocaine abuse with cocaine-induced psychotic disorder with delusions', 'Nondisplaced spiral fracture of shaft of humerus, unspecified arm, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'tristique', 'Nondisplaced fracture of right tibial tuberosity', 'eu', 'Unspecified fracture of unspecified pubis, sequela', 'Unspecified superficial injury of right elbow, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'in', 'Displaced fracture of cuboid bone of left foot, subsequent encounter for fracture with nonunion', 'nascetur', 'Laceration without foreign body of abdominal wall, right lower quadrant without penetration into peritoneal cavity, sequela', 'Strain of other muscles, fascia and tendons at forearm level, unspecified arm, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'semper', 'Laceration without foreign body of right front wall of thorax with penetration into thoracic cavity, initial encounter', 'maecenas', 'Pressure ulcer of unspecified elbow, stage 2', 'Puncture wound without foreign body, left hip', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'neque', 'Unspecified intracapsular fracture of unspecified femur, subsequent encounter for closed fracture with malunion', 'justo', 'Drowning and submersion due to fall off merchant ship, initial encounter', 'Skateboard accident', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'nulla', 'Laceration with foreign body of front wall of thorax with penetration into thoracic cavity', 'metus', 'Passenger in heavy transport vehicle injured in collision with other motor vehicles in nontraffic accident, subsequent encounter', 'Toxic effect of beryllium and its compounds, accidental (unintentional), initial encounter', 'Dislocation of interphalangeal joint of left lesser toe(s)', 'http://dummyimage.com/139x100.png/cc0000/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'nullam', 'Burn of unspecified degree of left elbow', 'arcu', 'Other bacterial diseases, not elsewhere classified', 'Physical abuse complicating the puerperium', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'donec', 'Complete traumatic amputation of two or more left lesser toes', 'hendrerit', 'Paralytic calcification and ossification of muscle, forearm', 'Infection and inflammatory reaction due to other cardiac and vascular devices, implants and grafts, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'in', 'Nondisplaced avulsion fracture (chip fracture) of right talus, initial encounter for closed fracture', 'velit', 'Exposure to prolonged high air pressure', 'Defects in glycoprotein degradation', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'id', 'Toxic effect of venom of other reptiles, intentional self-harm, subsequent encounter', 'sollicitudin', 'Displaced oblique fracture of shaft of unspecified femur, subsequent encounter for closed fracture with routine healing', 'Mature B-cell leukemia Burkitt-type not having achieved remission', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'tristique', 'Other traumatic displaced spondylolisthesis of fifth cervical vertebra, sequela', 'elementum', 'Military operations involving explosion of torpedo, military personnel, subsequent encounter', 'Skeletal fluorosis', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'nam', 'Infection and inflammatory reaction due to implanted electronic neurostimulator, generator, initial encounter', 'nec', 'Miscellaneous otorhinolaryngological devices associated with adverse incidents, not elsewhere classified', 'Idiopathic chronic gout, unspecified site, without tophus (tophi)', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (15, 'vivamus', 'Burn of second degree of left scapular region, initial encounter', 'libero', 'Type 1 diabetes mellitus with diabetic mononeuropathy', 'Unspecified injury of other blood vessels of thorax, unspecified side, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'quisque', 'Nondisplaced fracture of proximal phalanx of right great toe, initial encounter for open fracture', 'parturient', 'Burn of second degree of unspecified ankle', 'Blister (nonthermal), unspecified great toe, initial encounter', 'Burn of first degree of left elbow', 'http://dummyimage.com/215x100.png/cc0000/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'aenean', 'Triplet pregnancy with two or more monochorionic fetuses, second trimester', 'amet', 'Laceration with foreign body of right wrist', 'Pathological fracture in other disease, other site, subsequent encounter for fracture with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'sed', 'Nondisplaced oblique fracture of shaft of unspecified fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'est', 'Merkel cell carcinoma of other part of trunk', 'Underdosing of other synthetic narcotics, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'ligula', 'Other specified injury of muscle and tendon of long extensor muscle of toe at ankle and foot level, left foot, sequela', 'lacinia', 'Congenital malformations of great veins', 'Unspecified fracture of upper end of unspecified tibia, subsequent encounter for closed fracture with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'cursus', 'Complete loss of teeth due to trauma', 'purus', 'Partial traumatic transphalangeal amputation of right index finger', 'Encounter for other genetic testing of female for procreative management', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'cum', 'Abuse of other non-psychoactive substances', 'lacus', 'Stress fracture, left finger(s), subsequent encounter for fracture with routine healing', 'Nondisplaced comminuted fracture of shaft of left fibula, subsequent encounter for closed fracture with routine healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'condimentum', 'Other specified injury of intrinsic muscle and tendon at ankle and foot level, right foot, initial encounter', 'magna', 'Unspecified fracture of left patella, initial encounter for open fracture type IIIA, IIIB, or IIIC', 'Toxic effect of ingested berries, accidental (unintentional), initial encounter', 'Subluxation and dislocation of T12/L1 thoracic vertebra', 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'posuere', 'Unspecified fracture of lower end of unspecified femur', 'nunc', 'Other injury of extensor muscle, fascia and tendon of left ring finger at wrist and hand level', 'Other contact with turtle', 'External constriction of other part of head', 'http://dummyimage.com/143x100.png/5fa2dd/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (8, 'vel', 'Corrosion of third degree of left hand, unspecified site', 'adipiscing', 'Contact with mining and earth-drilling machinery, initial encounter', 'Posterior displaced Type II dens fracture, initial encounter for open fracture', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (1, 'quam', 'Other fracture of upper end of unspecified ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 'eget', 'Recurrent subluxation of patella, left knee', 'Reduced mobility', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (7, 'odio', 'Fracture of bone following insertion of orthopedic implant, joint prosthesis, or bone plate', 'quis', 'Toxic effect of unspecified inorganic substance, undetermined, subsequent encounter', 'Unspecified injury of intrinsic muscle, fascia and tendon of right little finger at wrist and hand level, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'amet', 'Chronic multifocal osteomyelitis, radius and ulna', 'ut', 'Colostomy infection', 'Other specified injury of unspecified blood vessel at forearm level, left arm, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'vestibulum', 'Other disorders of cartilage', 'mauris', 'Strain of other muscle(s) and tendon(s) of posterior muscle group at lower leg level, right leg, sequela', 'Injury of optic nerve, left eye, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'dignissim', 'Contusion of lung, unilateral, subsequent encounter', 'lorem', 'External constriction of foot', 'Insect bite (nonvenomous) of right upper arm, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'sed', 'External constriction, unspecified great toe, subsequent encounter', 'nullam', 'Yatapoxvirus infections', 'Displaced fracture of olecranon process with intraarticular extension of unspecified ulna', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (9, 'metus', 'Displaced spiral fracture of shaft of right tibia, subsequent encounter for open fracture type I or II with routine healing', 'posuere', 'Toxic effect of halogenated insecticides, accidental (unintentional)', 'Staphylococcal polyarthritis', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (7, 'ante', 'Mechanical loosening of internal left hip prosthetic joint, subsequent encounter', 'consequat', 'Corrosion of second degree of lower back, subsequent encounter', 'Displaced fracture of greater trochanter of unspecified femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'sagittis', 'Other superficial bite of right ring finger', 'non', 'Benign neoplasm of unspecified bronchus and lung', 'Terrorism involving chemical weapons, public safety official injured, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'duis', 'Pruritus', 'amet', 'Burn of first degree of left hand, unspecified site, initial encounter', 'Perforation due to foreign body accidentally left in body following aspiration, puncture or other catheterization, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'elementum', 'Other malformation of placenta, unspecified trimester', 'nonummy', 'Fibrous dysplasia (monostotic), right lower leg', 'Toxic effect of ingested berries, intentional self-harm', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'porta', 'Unspecified open wound of nose, subsequent encounter', 'proin', 'Nondisplaced spiral fracture of shaft of ulna, unspecified arm, initial encounter for closed fracture', 'Benign neoplasm of unspecified part of small intestine', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'viverra', 'Toxic effect of mercury and its compounds, undetermined', 'at', 'Nondisplaced fracture of olecranon process with intraarticular extension of left ulna, subsequent encounter for closed fracture with nonunion', 'Contusion of toe without damage to nail', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'sed', 'Displaced midcervical fracture of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 'a', 'Unspecified intracranial injury with loss of consciousness of 6 hours to 24 hours, sequela', 'Meningitis due to other and unspecified causes', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'pellentesque', 'Pneumatic hammer syndrome, initial encounter', 'nec', 'Toxic effect of unspecified gases, fumes and vapors', 'Other dislocation of unspecified radial head, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'vestibulum', 'Increased secretion of gastrin', 'ante', 'Unspecified injury of muscle, fascia and tendon of the posterior muscle group at thigh level, left thigh, initial encounter', 'Secondary malignant neoplasm of left adrenal gland', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'ultrices', 'Retained (old) foreign body following penetrating wound of left orbit', 'turpis', 'Unspecified open wound of left thumb without damage to nail, initial encounter', 'Poisoning by other antidepressants, intentional self-harm, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'turpis', 'Other and unspecified sprain of wrist', 'duis', 'Wedge compression fracture of fourth thoracic vertebra, subsequent encounter for fracture with routine healing', 'Machinery accident on board unspecified watercraft, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'in', 'Crushing injury of unspecified hip, sequela', 'fusce', 'Corrosion of unspecified degree of scalp [any part]', 'Laceration of intercostal blood vessels, unspecified side, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (2, 'ante', 'Subluxation of metacarpophalangeal joint of right index finger', 'vel', 'Salter-Harris Type I physeal fracture of upper end of left femur, sequela', 'Ultralight, microlight or powered-glider fire injuring occupant, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'aliquam', 'Atrophy of unspecified orbit', 'posuere', 'Kaschin-Beck disease, right wrist', 'Displaced spiral fracture of shaft of unspecified tibia, initial encounter for open fracture type I or II', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'quam', 'Carbuncle of right lower limb', 'at', 'Corrosion of unspecified degree of left wrist, subsequent encounter', 'Local infection due to central venous catheter, subsequent encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (6, 'ut', 'Subluxation and dislocation of ankle joint', 'ullamcorper', 'Adult osteochondrosis of spine, sacral and sacrococcygeal region', 'Person on outside of car injured in collision with railway train or railway vehicle in nontraffic accident, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'scelerisque', 'Burn of unspecified degree of buttock', 'penatibus', 'Macrocheilia', 'Cutaneous and mucocutaneous bartonellosis', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (13, 'aliquet', 'Benign neoplasm of left ureter', 'amet', 'Other fatigue', 'Foreign body in cornea, right eye, initial encounter', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (17, 'amet', 'Osteonecrosis in diseases classified elsewhere, multiple sites', 'nunc', 'Other disorders of adult personality and behavior', 'Burn of first degree of forehead and cheek, sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (12, 'id', 'Leishmaniasis, unspecified', 'in', 'Leakage of insulin pump', 'Poisoning by anticoagulant antagonists, vitamin K and other coagulants, accidental (unintentional), sequela', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (20, 'orci', 'Puncture wound without foreign body of oral cavity, initial encounter', 'integer', 'Poisoning by unspecified fibrinolysis-affecting drugs, intentional self-harm', 'Maternal care for (suspected) central nervous system malformation in fetus, fetus 5', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (3, 'sapien', 'Salter-Harris Type III physeal fracture of lower end of humerus, unspecified arm, subsequent encounter for fracture with malunion', 'nulla', 'Round hole of retina without detachment', 'Displaced fracture of lateral condyle of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (4, 'velit', 'Other superficial bite of ankle, unspecified ankle', 'ultrices', 'Person injured in unspecified motor-vehicle accident, nontraffic', 'Non-pressure chronic ulcer of unspecified calf with unspecified severity', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'sed', 'Subluxation of T10/T11 thoracic vertebra, sequela', 'sed', 'Osteomyelitis of vertebra, cervical region', 'Folds and rupture in Bowman''s membrane', 'Mantle cell lymphoma, intra-abdominal lymph nodes', 'http://dummyimage.com/167x100.png/5fa2dd/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (10, 'nullam', 'Urogenital trichomoniasis', 'tristique', 'Superficial frostbite of ankle', 'Fracture of lower epiphysis (separation) of femur', null, null);
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (19, 'luctus', 'Stenosis of other vascular prosthetic devices, implants and grafts', 'in', 'Displaced comminuted fracture of shaft of right fibula, sequela', 'Unspecified occupant of heavy transport vehicle injured in collision with unspecified motor vehicles in traffic accident, sequela', 'Infantile acne', 'http://dummyimage.com/148x100.png/cc0000/ffffff');
insert into flashcard (fc_set_id, word, meaning, type_of_word, pronounce, example, note, image) values (11, 'egestas', 'Other fracture of fourth lumbar vertebra', 'accumsan', 'Other fracture of shaft of radius, unspecified arm, subsequent encounter for open fracture type I or II with routine healing', 'Monoplegia of lower limb following nontraumatic subarachnoid hemorrhage affecting left non-dominant side', null, null);


-- Learnt list
create table learnt_list (
	fc_id INT REFERENCES flashcard(fc_id) ON DELETE CASCADE,
	user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fc_id, user_id)
);
insert into learnt_list (fc_id, user_id) values (35, 9);
insert into learnt_list (fc_id, user_id) values (83, 16);
insert into learnt_list (fc_id, user_id) values (55, 20);
insert into learnt_list (fc_id, user_id) values (83, 15);
insert into learnt_list (fc_id, user_id) values (129, 15);
insert into learnt_list (fc_id, user_id) values (56, 11);
insert into learnt_list (fc_id, user_id) values (88, 2);
insert into learnt_list (fc_id, user_id) values (45, 12);
insert into learnt_list (fc_id, user_id) values (98, 13);
insert into learnt_list (fc_id, user_id) values (45, 14);
insert into learnt_list (fc_id, user_id) values (166, 3);
insert into learnt_list (fc_id, user_id) values (155, 2);
insert into learnt_list (fc_id, user_id) values (188, 6);
insert into learnt_list (fc_id, user_id) values (196, 6);
insert into learnt_list (fc_id, user_id) values (147, 17);
insert into learnt_list (fc_id, user_id) values (35, 19);
insert into learnt_list (fc_id, user_id) values (49, 5);
insert into learnt_list (fc_id, user_id) values (152, 10);
insert into learnt_list (fc_id, user_id) values (19, 2);
insert into learnt_list (fc_id, user_id) values (52, 18);
insert into learnt_list (fc_id, user_id) values (49, 14);
insert into learnt_list (fc_id, user_id) values (170, 19);
insert into learnt_list (fc_id, user_id) values (189, 3);
insert into learnt_list (fc_id, user_id) values (163, 10);
insert into learnt_list (fc_id, user_id) values (116, 17);
insert into learnt_list (fc_id, user_id) values (99, 13);
insert into learnt_list (fc_id, user_id) values (81, 2);
insert into learnt_list (fc_id, user_id) values (108, 18);
insert into learnt_list (fc_id, user_id) values (174, 16);
insert into learnt_list (fc_id, user_id) values (13, 4);
insert into learnt_list (fc_id, user_id) values (25, 18);
insert into learnt_list (fc_id, user_id) values (154, 16);
insert into learnt_list (fc_id, user_id) values (66, 1);
insert into learnt_list (fc_id, user_id) values (194, 13);
insert into learnt_list (fc_id, user_id) values (158, 19);
insert into learnt_list (fc_id, user_id) values (85, 5);
insert into learnt_list (fc_id, user_id) values (147, 20);
insert into learnt_list (fc_id, user_id) values (174, 12);
insert into learnt_list (fc_id, user_id) values (37, 3);
insert into learnt_list (fc_id, user_id) values (10, 15);
insert into learnt_list (fc_id, user_id) values (85, 4);
insert into learnt_list (fc_id, user_id) values (29, 2);
insert into learnt_list (fc_id, user_id) values (169, 20);
insert into learnt_list (fc_id, user_id) values (19, 3);
insert into learnt_list (fc_id, user_id) values (191, 19);
insert into learnt_list (fc_id, user_id) values (163, 5);
insert into learnt_list (fc_id, user_id) values (123, 3);
insert into learnt_list (fc_id, user_id) values (81, 20);
insert into learnt_list (fc_id, user_id) values (135, 17);
insert into learnt_list (fc_id, user_id) values (157, 19);
insert into learnt_list (fc_id, user_id) values (50, 12);
insert into learnt_list (fc_id, user_id) values (1, 10);
insert into learnt_list (fc_id, user_id) values (131, 17);
insert into learnt_list (fc_id, user_id) values (125, 8);
insert into learnt_list (fc_id, user_id) values (23, 9);
insert into learnt_list (fc_id, user_id) values (193, 3);
insert into learnt_list (fc_id, user_id) values (182, 9);
insert into learnt_list (fc_id, user_id) values (120, 13);
insert into learnt_list (fc_id, user_id) values (57, 3);
insert into learnt_list (fc_id, user_id) values (63, 12);
insert into learnt_list (fc_id, user_id) values (57, 1);
insert into learnt_list (fc_id, user_id) values (152, 12);
insert into learnt_list (fc_id, user_id) values (111, 6);
insert into learnt_list (fc_id, user_id) values (113, 6);
insert into learnt_list (fc_id, user_id) values (143, 9);
insert into learnt_list (fc_id, user_id) values (165, 10);
insert into learnt_list (fc_id, user_id) values (77, 20);
insert into learnt_list (fc_id, user_id) values (145, 9);
insert into learnt_list (fc_id, user_id) values (44, 2);
insert into learnt_list (fc_id, user_id) values (11, 18);
insert into learnt_list (fc_id, user_id) values (110, 3);
insert into learnt_list (fc_id, user_id) values (119, 20);
insert into learnt_list (fc_id, user_id) values (139, 1);
insert into learnt_list (fc_id, user_id) values (5, 20);
insert into learnt_list (fc_id, user_id) values (19, 20);
insert into learnt_list (fc_id, user_id) values (87, 9);
insert into learnt_list (fc_id, user_id) values (38, 2);
insert into learnt_list (fc_id, user_id) values (4, 10);
insert into learnt_list (fc_id, user_id) values (65, 2);
insert into learnt_list (fc_id, user_id) values (146, 13);
insert into learnt_list (fc_id, user_id) values (192, 3);
insert into learnt_list (fc_id, user_id) values (192, 11);
insert into learnt_list (fc_id, user_id) values (173, 15);
insert into learnt_list (fc_id, user_id) values (155, 19);
insert into learnt_list (fc_id, user_id) values (62, 12);
insert into learnt_list (fc_id, user_id) values (171, 4);
insert into learnt_list (fc_id, user_id) values (139, 9);
insert into learnt_list (fc_id, user_id) values (153, 14);
insert into learnt_list (fc_id, user_id) values (193, 11);
insert into learnt_list (fc_id, user_id) values (130, 9);
insert into learnt_list (fc_id, user_id) values (61, 2);
insert into learnt_list (fc_id, user_id) values (184, 11);
insert into learnt_list (fc_id, user_id) values (10, 18);
insert into learnt_list (fc_id, user_id) values (112, 16);
insert into learnt_list (fc_id, user_id) values (56, 12);
insert into learnt_list (fc_id, user_id) values (155, 18);
insert into learnt_list (fc_id, user_id) values (46, 11);
insert into learnt_list (fc_id, user_id) values (186, 9);
insert into learnt_list (fc_id, user_id) values (17, 15);
insert into learnt_list (fc_id, user_id) values (141, 14);
